### ISSUE TITLE
UI feedback shows 5 minutes in the future, but the actual deployment is scheduled for 15 minutes in the future.

### ISSUE THREAD

**Issue by Joble** [SalesforceFoundation/CumulusCI#442] opened 2017-09-19 14:47 UTC
Below is the output of a push command given with no set start time. It shows a default start time of 5 minutes from the time of the command, but the reality is that the deployment is scheduled for 15 minutes from the time of the command. The resulting deployment from the command below was set to start at 15:03, not 14:48.

> $ cci task run push_oneoff -o version 3.50
2017-09-19 10:43:28: Beginning task: SchedulePushOrgList
2017-09-19 10:43:28:        As user: jgoble.pkg@salesforce.com
2017-09-19 10:43:28:         In org: 00D400000008HjXEAU
2017-09-19 10:43:28: 
2017-09-19 10:43:28: Scheduling push for 5 minutes from now
2017-09-19 10:43:29: Found 1 orgs
2017-09-19 10:43:29: Batch 1 of 1: Attempting to add 1 orgs
2017-09-19 10:43:29: 1 orgs successfully added to batch
2017-09-19 10:43:29: Push request 0DV1W000000bldx is populated with 1 orgs
2017-09-19 10:43:29: Setting status to Pending to queue execution.
2017-09-19 10:43:29: The push upgrade will start at UTC 2017-09-19 14:48:28.929731
2017-09-19 10:43:29: 204
2017-09-19 10:43:29: Push Request 0DV1W000000bldx is queued for execution.
2017-09-19 10:43:29: Exiting early since request is in the future

**Comment by cpolcyn** [comment] 2017-09-19 16:39
Duplicate of https://github.com/SalesforceFoundation/CumulusCI/issues/375

**Closed by cpolcyn** 2017-09-19 16:39 UTC
Labels: duplicate
