### ISSUE TITLE
Add Project Root Directory to Python Path

### ISSUE THREAD

**Issue by craigargh** [SalesforceFoundation/CumulusCI#239] opened 2017-02-28 14:41 UTC
Custom tasks in the repository do not work as per the documentation. This is because the project's root directory is not added to the Python path.

To fix this, add the following line to the import_class() function in the core/utils.py before calling \_\_import\_\_()

`sys.path.append(os.getcwd())`

**Comment by cdcarter** [comment] 2017-02-28 17:11
We should be adding the repo_root to Python Path during Cli initialization: https://github.com/SalesforceFoundation/CumulusCI/blob/master/cumulusci/cli/cli.py#L56. This worked at one time. 

I'm trying to repro locally now.

**Comment by cdcarter** [comment] 2017-02-28 17:15
I followed the tutorial exactly and this worked for me. Could you post your dir structure and how you have it wired up in cumulusci.yml?

**Comment by craigargh** [comment] 2017-03-02 10:22
The yml for the task (project details changed):
`project:
    name: Test Project
    package:
        name: Test Package
        namespace: testpackage

tasks:
  output_message:
    description: Output a message to the log
    class_path: tasks.rest.SayHello
`

`tasks` folder in the root directory with the following in that directory:

- \_\_init\_\_.py
- rest.py

Contents of rest.py. 
`from cumulusci.tasks.salesforce import BaseSalesforceApiTask


class SayHello(BaseSalesforceApiTask):
    def _run_task(self):
        self.logger.info("Hello")
`

The tutorial gives the wrong location for the BaseSalesforceApiTask class.

**Comment by craigargh** [comment] 2017-03-02 11:04
I added this to `_add_repo_to_path()`:
```
print "repo root: " + self.project_config.repo_root
```

This is the output:
```
repo root: C:
```

**Comment by cdcarter** [comment] 2017-03-02 16:55
It's quite possible this implementation actually hasn't been tested on a Windows setup... Thank you for finding this!

Could you send some environment details so I can standup a VM and reproduce? Version of Windows, where you installed Python, what shell are you running (i.e. cmd.exe, powershell, the linux thingy....)?

**Comment by craigargh** [comment] 2017-03-07 10:51
I'm using Windows 10 and a Python 2.7.11 virtual environment. I've tried running the command on cmder, Powershell and PyCharm with the same result in each.

**Comment by cdcarter** [comment] 2017-03-07 17:29
Thanks Craig, I'll take a look. You can see from Chris's tag that we're aware that windows docs and usage is lacking right now. There are other problems you could face when repo_root isn't functioning, not just related to imports, so we wanna get this working.

**Comment by jlantz** [comment] 2017-03-22 16:21
Fixed in beta23

**Comment by cpolcyn** [comment] 2017-03-22 17:25
Reopening because the core issue is that self.project_config.repo_root returns unexpected value (e.g. "C:") on Windows. We should fix this in cumulusci/core/config.py BaseProjectConfig.repo_root then the changes from a386604 and a2f9419 should be removed.

**Comment by cpolcyn** [comment] 2017-03-22 20:54
Turns out it was not related to os.getcwd(). The problem is that the drive was being handled as part of the path and when joined back together was incorrect. For example "C:Users\\Chris\\MyProject" instead of "C:\\Users\\Chris\\MyProject".

**Closed** 2017-03-27 20:46 UTC
Labels: bug, Windows
