### ISSUE TITLE
Scratch org password not being updated where created in a flow

### ISSUE THREAD

**Issue by topherlandry** [SalesforceFoundation/CumulusCI#641] opened 2018-05-28 20:08 UTC
Since this change (https://github.com/SalesforceFoundation/CumulusCI/commit/fde28ca7345e9ef052dffdbebc20d5247910a261) I've not been able to get a new scratch org password generated when creating an org with the `dev_org` flow. When the new scratch org is created, it is created with a new password, but org info does not display the new password.

`cci org info dev` will give me the password of a previous org instead of the new one and I find that I'm not actually able to log in with the new credentials.

Based on what I'm looking at, it looks like when `BaseFlow` goes to refresh the oauth token and finds no scratch org, it runs `create_org` in `ScratchOrgConfig`. `cci org scratch dev org_name` uses `create_scratch_org` in the keychain, so it makes sense that the password generation is being handled differently.

I've reverted this change locally and everything has gone back to working as expected.
This is still true after the changes in #639.

**Comment by cpolcyn** [comment] 2018-05-30 16:45
I'm unable to reproduce the issue as of 4370d869b07877d22d2e7840db5fd85d4b376155. Here are my steps:

```bash
$ cci org scratch dev org_name
$ cci org info org_name
$ cci org scratch_delete org_name
$ cci flow run dev_org --org org_name
$ cci org info org_name
```

When I do this I can see the username and password have been updated, and logging in with the new credentials works.

I'm closing this one but please feel free to continue conversation here if needed.

**Closed by cpolcyn** 2018-05-30 16:45 UTC
